#### general settings
name: ir-sde
use_tb_logger: true
model: denoising
distortion: AR2OR
gpu_ids: [1]

sde:
  max_sigma: 30 # 10
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4

#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /home/y/桌面/IR-SDE-data/4_29/train/GT
    dataroot_LQ: /home/y/桌面/IR-SDE-data/4_29/train/55um_35db

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 2
    GT_size: 256
    LR_size: 256
    use_flip: true
    use_rot: true
    color: gray
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /home/y/桌面/IR-SDE-data/4_29/test/GT
    dataroot_LQ: /home/y/桌面/IR-SDE-data/4_29/test/55um_35db


#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    depth: 4

#### path
path:
  experiments_root: /home/y/桌面/image-restoration-sde/codes/config/AR2OR/AAA_ckpt/429/55um_35db
  resume_state: ~

  pretrain_model_G: ~
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 700000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
