#### general settings
name: refusion
use_tb_logger: true
model: denoising
distortion: AR2OR
gpu_ids: [0]

sde:
  max_sigma: 50 # 50
  T: 100 # 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  train:
    optimizer: Lion # Adam, AdamW, Lion
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /home/y/桌面/IR-SDE-data/5_15/GT
    dataroot_LQ: /home/y/桌面/IR-SDE-data/5_15/55um_15db

    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 2
    GT_size: 256
    LR_size: 256
    use_flip: false
    use_rot: false
    color: gray
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /home/y/桌面/IR-SDE-data/5_15_test/GT
    dataroot_LQ: /home/y/桌面/IR-SDE-data/5_15_test/55um_15db

network_G:
  which_model_G: ConditionalNAFNet
  setting:
    width: 64
    enc_blk_nums: [1, 1, 1, 28]
    middle_blk_num: 1
    dec_blk_nums: [1, 1, 1, 1]

#### path
path:
  experiments_root: /home/y/桌面/image-restoration-sde/codes/config/AR2OR/AAA_ckpt/5_15/55um_15db
  resume_state: ~

  pretrain_model_G: ~
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  optimizer: Lion # Adam, AdamW, Lion（原）
  lr_G: !!float 4e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 700000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3
#  val_freq: 5

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
